# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a70c6adfe5c3e80810f15cb9ecd9bf873417f1f8da5ac9f317a1376f71ae539a6f42b682562d6db31c2d7cbf63ed9eff277d4373f94debed7bc7c884ceb9cdb

test:
  secret_key_base: 996b7eea19f4b1b2542ce682b945a6a0555d3be78ad84f1b7a8cc9df4933302e49bbdc964a3ddb9a27286252815c2ba8b81178eeddbab247a2ed8bd6abc5d9e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
